---
title: "eeda demonstration dashboard"
output: 
  flexdashboard::flex_dashboard:
    theme: bootstrap
    orientation: columns
    vertical_layout: scroll
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(knitr)
library(eeda)

target_var <- "target"
reference_var <- c("key_age", "key_recency", "key_frequency", "key_monetary")
study_variables <-
  names(eeda_test_data %>%
    dplyr::select(-tidyselect::any_of(c(target_var))))
```

```{r results="asis"}
curios::add_custom_style()
```

```{r results="asis"}
eeda::extra_eda(eeda_test_data,
  eda_var = "target",
  menu_title = "Univariate"
)
```

```{r results="asis"}
# study_variables %>%
"eg_factor_50" %>% 
  furrr::future_walk(~ eeda::extra_eda(eeda_test_data[1:200, ],
    eda_var = .x,
    target_var = target_var,
    reference_var = reference_var,
    menu_title = "Bivariate"
  ),
  .options = furrr::furrr_options(seed = NULL)
  )
```




```{r}

eeda::extra_eda(df = 
 left_join(data$engineered,
            health_context_index,
            by = "Member_Id_Universal"),
  eda_var = "Health_Context_Index",
  target_var = "Medical_3rd_Highest_Month",
    reference_var = c( 
      # "Age",
                       # "Sex",
                       # "Is_Minority"
                       # "Chronic_Condition_Cnt",
                       # "HbA1c",
                      "HTOW_Index"
                       # "RS_Medical_Prosp_Risk_Score",
                       # "RS_Pharmacy_Prosp_Risk_Score",
                       # "ED_Per_PCP1",
                       # "Medical_3rd_Highest_Month",
                       # "Pharmacy_3rd_Highest_Month",
                       # "LN_SDOH_Socio_Index",
                       # "LN_SDOH_Readmission_Probability",
                       # "LN_SDOH_Medication_Adherence_Rate",
                       # "LN_SDOH_Motivation_Level"
                       ),
  menu_title = "Bivariate"
)
```

