---
title: "eeda demonstration dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
    source_code: embed
vignette: >
  %\VignetteIndexEntry{eeda}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
library(flexdashboard)
library(eeda)
```

<style>
/* Adjust ### headers created in flexdashboard */
    .chart-title {
    /* border-bottom: 1px solid #d7d7d7; */
    border-bottom: none;
    color: #000000;
    font-family: Arial, Helvetica, sans-serif;
    font-size: 22px;
    font-weight: 700;
    padding: 7px 0px 0px 7px;
    margin-top: 60px; /* fixes relative link landing on page and hiding heading*/
    }
</style>

# Univariate

```{r results="asis"}
# foo = function(df, eda_column){
#   cat(sum(is.na(df[eda_column])), eda_column, "\n")
# }
# foo(eeda_test_data[1:200,], eda_column = "bar")
# names(eeda_test_data) %>%
#   furrr::future_walk(~ foo(eeda_test_data[1:200,], eda_column = .x))

# eeda::extra_eda(df = eeda::eeda_test_data[1:200,], eda_column = "eg_factor_50")

# names(eeda_test_data) %>%
#   furrr::future_walk(~ eeda::extra_eda(eeda_test_data[1:200,], eda_column = .x),
#                      seed = NULL)
```

# Bivariate

```{r results="asis"}
target_var <- "target"
reference_var <- c("key_age", "key_recency", "key_frequency", "key_monetary")

names(eeda_test_data %>%
  dplyr::select(-tidyselect::any_of(c(target_var, "key_age"))))[1:18] %>%
  furrr::future_walk(~ eeda::extra_eda(eeda_test_data[1:200, ],
    eda_var = .x,
    target_var = target_var,
    reference_var = reference_var
  ),
  .options = furrr::furrr_options(seed = NULL)
  )
```
